### ISSUE TITLE
"Unexpected SPDX error parsing license string" with certain license identifiers

### ISSUE THREAD

**Issue by alpianon** [spdx/tools#272] opened 2021-03-22 08:21 UTC
While intensively using spdx-tools' TagToRDF function, I encountered an `Unexpected SPDX error parsing license string` (which causes rdf file creation to stop) when trying to convert SPDX TagValue files containing one or more of the following license identifiers:

- MIT-open-group
- X11
- BSD-2-Clause-Views
- MulanPSL-2.0

This list may not be complete; they are just the problematic licenses I found so far.

The log information (even activating debug loglevel) does not tell anything relevant to understand the cause of the error; with debug loglevel, I noticed the parser stopped working after parsing a certain license identifier, so I tried to manually remove that license identifier from the SPDX file and re-run TagToRDF, and I noticed that in that way it worked.

I attach some spdx-tv files affected by this issue: [spdx-tv_samples.zip](https://github.com/spdx/tools/files/6180512/spdx-tv_samples.zip)

For my tests, I used the latest release file `spdx-tools-2.2.4-jar-with-dependencies.jar`

sample commands:

```bash
java -jar /usr/local/lib/spdx-tools-2.2.4-jar-with-dependencies.jar TagToRDF kernel-liteos-m_2021.03.22-scancode.spdx kernel-liteos-m_2021.03.22-scancode.spdx.rdf

# with debug loglevel:
java -Dlog4j.configurationFile=./log4j2-debug.xml -jar /usr/local/lib/spdx-tools-2.2.4-jar-with-dependencies.jar TagToRDF kernel-liteos-m_2021.03.22-scancode.spdx kernel-liteos-m_2021.03.22-scancode.spdx.rdf

```

**Comment by goneall** [comment] 2021-03-22 17:09
In doing some quick debugging, it seems that there is an issue trying to fetch the license data from the [License List website](https://spdx.org/licenses/) for the MulanPSL-2.0 license.

I'll do a bit more digging later today or tomorrow to see if I can find the root cause.

**Comment by goneall** [comment] 2021-03-22 17:10
BTW - I noticed the tag/value file is missing the required SPDX ID's for the files.  This causes the newer version of this utility to trip up.  Otherwise, I would encourage you to try the [tools-java](https://github.com/spdx/tools-java) version which is a bit more supportable.

**Comment by goneall** [comment] 2021-03-22 17:25
Getting closer to the root cause - the JSON-LD on the license list website do not contain a LicenseID field.  The JSON representation, however, does contain the LicenseID field.  The new tools-java utility uses JSON and doesn't have the same issue.

I'll look into why the LicenseListPublisher is not serializing the License ID in the JSON-LD format.

**Comment by goneall** [comment] 2021-03-22 21:53
Resolved with PR #273 

@alpianon let me know if you would like me to spin another release including this fix

**Comment by alpianon** [comment] 2021-03-23 08:33
thx @goneall !  It would be nice to have a fix for #268 included in a new release, too

**Comment by goneall** [comment] 2021-03-26 17:13
Resolved in [release 2.2.5](https://github.com/spdx/tools/releases/tag/v2.2.5)

**Closed by goneall** 2021-03-26 17:13 UTC

**Comment by alpianon** [comment] 2021-03-27 11:55
@goneall thanks so much: tested, it works!

Would it be possible for you to add to v2.2.5 release artifacts also the built jar `spdx-tools-2.2.5-jar-with-dependencies.jar` like in the previous releases, just for convenience?
Thanks!

**Comment by goneall** [comment] 2021-03-27 15:29
@alpianon you're welcome

> Would it be possible for you to add to v2.2.5 release artifacts also the built jar spdx-tools-2.2.5-jar-with-dependencies.jar like in the previous releases, just for convenience?

Done

**Comment by alpianon** [comment] 2021-03-30 15:12
thx!
